import type { InterviewReport, StoredSession } from "./schemas";

function score(answer: string) { const words = answer.trim().split(/\s+/).filter(Boolean).length; return Math.min(92, Math.max(42, 45 + Math.min(100, words) / 3 + (/\d|%|measured|metric/i.test(answer) ? 10 : 0) + (/\bI (led|owned|built|created|decided)/i.test(answer) ? 7 : 0))); }
function improved(answer: string) { const clean = answer.trim(); return clean ? `Lead with: “${clean.match(/^.*?[.!?](?:\s|$)/)?.[0]?.trim() ?? clean}” Then add: [specific situation], [your personal action], and [insert measurable result] only if those details are accurate.` : "Situation: [insert relevant situation]. Action: [insert your personal action]. Result: [insert measurable result or observable evidence]."; }

export function createReport(session: StoredSession): InterviewReport {
  const entries = session.transcript.filter((entry) => !entry.skipped && entry.answer.trim());
  const average = entries.length ? Math.round(entries.reduce((total, entry) => total + score(entry.answer), 0) / entries.length) : 0;
  const evidence = entries.filter((entry) => /\d|%|measured|metric/i.test(entry.answer)).length;
  return { score: average, readiness: average >= 78 ? "Ready to practice live" : average >= 60 ? "Promising foundation" : "Build more evidence", summary: entries.length ? "You showed a credible operating profile. The next step is making ownership, choices, and evidence more explicit in each story." : "No answers were submitted, so this report uses preparation placeholders.", strongestDimension: evidence ? "Evidence-aware operating impact" : "Relevant strategic operations experience", improvementArea: "Make your personal role and the evidence behind outcomes unmistakable.", competencies: [{ label: "Structured communication", score: Math.min(90, average + 3) }, { label: "Strategic judgment", score: average }, { label: "Stakeholder leadership", score: Math.max(35, average - 2) }, { label: "Impact orientation", score: Math.max(30, average + (evidence ? 4 : -8)) }], concerns: [evidence < entries.length ? "Several outcomes need a metric, baseline, or observable indicator." : "Connect each metric more directly to your own decision.", "Avoid describing team work with “we” without naming your ownership."], stories: session.transcript.filter((entry) => /\b(led|built|launched|coordinated|created)\b/i.test(entry.answer)).map((entry) => entry.question.prompt).slice(0, 3).concat(entries.length ? [] : ["[prepare one strategic initiative with a measurable outcome]"]), actions: ["Prepare two concise stories using situation → personal action → result.", "For every outcome, write down the metric, baseline, or observable evidence you can defend.", "Practice naming the decision you owned before describing the team's work."], questions: session.transcript.map((entry) => ({ question: entry.question.prompt, answer: entry.skipped ? "[Skipped]" : entry.answer || "[No answer provided]", worked: entry.answer ? "You engaged with the topic and created material to refine." : "No answer was available to assess.", weakened: /\bwe\b/i.test(entry.answer) && !/\bI (led|owned|built|created|decided)/i.test(entry.answer) ? "Your personal ownership was not yet clear." : !/\d|%|measured|metric/i.test(entry.answer) ? "The answer needs verifiable evidence or an explicit placeholder." : "The answer could lead with its conclusion more directly.", structure: "Situation → your personal role → decision or action → evidence of result.", improvedExample: improved(entry.answer) })) };
}
